a3_group53/EventsAround/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from .forms import LoginForm,RegisterForm
from flask_login import login_user, login_required,logout_user
from . import db

#create a blueprint
bp = Blueprint('auth', __name__)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form submis is fine
    if (register.validate_on_submit() == True):
            #get username, password and email from the form
            uname =register.user_name.data
            pwd = register.password.data
            email=register.email_id.data
            #check if a user exists
            u1 = User.query.filter_by(name=uname).first()
            if u1:
                flash('User name already exists, please login')
                return redirect(url_for('auth.login'))
            # don't store the password - create password hash
            pwd_hash = generate_password_hash(pwd)
            #create a new user model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when there is a get message
    else:
        return render_template('user.html', form=register, heading='Register')
    
# this is a hint for a login function
@bp.route('/login', methods=['GET', 'POST'])
def login(): #view function
    print('In Login View function')
    login_form = LoginForm()
    error=None
    if(login_form.validate_on_submit()==True):
        user_name = login_form.user_name.data
        password = login_form.password.data
        user = User.query.filter_by(name=user_name).first()
        if user is None:
            error='Incorrect credentials supplied'
        elif not check_password_hash(user.password_hash, password): # takes the hash and password
            error='Incorrect credentials supplied'
        if error is None:
            login_user(user)
            return redirect(url_for('main.index'))
            # nextp = request.args.get('next') #this gives the url from where the login page was accessed
            # print(nextp)
            # if next is None or not nextp.startswith('/'):
            #     return redirect(url_for('index'))
            # return redirect(nextp)
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return 'You have been logged out'

a3_group53/EventsAround/views.py
from flask import Blueprint, render_template, request, redirect,url_for
from .models import Event


mainbp = Blueprint('main', __name__)


@mainbp.route('/')
def index():
    events = Event.query.all()    
    return render_template('index.html', events=events)
    #TODO: add filtering

@mainbp.route('/search')
def search():
    if request.args['search']:
        print(request.args['search'])
        evnt = "%" + request.args['search'] + '%'
        events = Event.query.filter(Event.description.like(evnt)).all()
        return render_template('index.html', events=events)
    else:
        return redirect(url_for('main.index'))

a3_group53/EventsAround/templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AT3 - Events Around</title>
    <!-- My custom stylesheet -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/styles.css') }}">

    <!-- Style for search button-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- script to bring nav bar to life-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</head>

</head>

<body>
    <!-- Header -->
    <header class="bg-light border-bottom">

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">

                <!-- Add logo -->
                <a href="/" class="navbar-brand">
                    EventsAround.com
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar -->
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <div class="navbar-nav ml-auto">

                        <a class="nav-item nav-link" href="/">Home</a>

                        <!-- Register/Login/Logout and welcome -->
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link disabled text-muted" href="#">Welcome {{current_user.name}}</a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                        {% endif %}
                        <!-- Event create and booking history -->
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('event.create') }}"> Event</a> <!---->
                        <a class="nav-item nav-link" href="{{ url_for('order.history') }}">Booking History</a> <!---->
                        {% else %} {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>



    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>


<footer class="footer">
    <div class="text-center py-2 bg-light">
        <span class="text-dark">Copyright &copy; 2023 - by Group 53</span>
    </div>
</footer>

</html>

a3_group53/EventsAround/templates/index.html
{% extends 'base.html' %}

{% block header %}
<!--Jumbotron-->
<div class="container">
   <div class="row justify-content-center mt-5 pb-4">
      <div class="col-md-8">
         <div class="card shadow p-5 mb-5 bg-light">
            <h1 class="text-center mb-3">Find our best travel deals</h1>

            <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}">
               <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm1">
               <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
            </form>

         </div>
      </div>
   </div>
</div>
{% endblock %}

{% block content %}
<!--Jumbotron-->
<div class="container">
   <div class="row justify-content-center mt-5 pb-4">
      <div class="col-md-8">
         <div class="card shadow p-5 mb-5 bg-light">
            <h1 class="text-center mb-3">Let Us take care of Your plans!</h1>
            </select>
            <button a type="submit" class="flex-shrink-1 btn btn-primary btn-light-blue ms-2" id="randomNumber">Try your luck!</button>
            </form>
         </div>
      </div>
   </div>
</div>
<div class="container col-md-6">
   <!-- Search -->

   <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}" >
      <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm2">
      <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Search</button>
    </form>
</div>
</header>

<!-- Category search buttons -->
<div class="chevron-container" >

   <form class="chevron-orange-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="career" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Career</button>
   </form>

   <form class="chevron-orange-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="Health" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Health</button>
   </form>

   <form class="chevron-orange-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="Sales" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Sales</button>
   </form>

   <form class="chevron-orange-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="Tradeshows" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Tradeshows</button>
   </form>

   <form class="chevron-orange-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="Business" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Business</button>
   </form>

</div>
</div>

<div class="chevron-container">

   <form class="chevron-blue-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="Networking" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Networking</button>
   </form>

   <form class="chevron-blue-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="Education" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Education</button>
   </form>

   <form class="chevron-blue-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="Marketing" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Marketing</button>
   </form>

   <form class="chevron-blue-right" name="search" action="{{url_for('main.search')}}">
      <input type="text" name="search" value="Innovation" class="form-control flex-grow-1 my-1 mr-sm-2" >
      <button class="chevron-text" >Innovation</button>
   </form>

</div>

<!-- Add the title "Popular business events in your area" here -->
<h2 class="text-center mb-4">Popular Business and Networking events in your area:</h2>
<div class="container">

   <div class="card-body">
      {% for event in events %}
      <div class="card mx-3" style="margin-bottom: 4rem;">
         <img class="card-img-top" src="{{ event.image }}" alt="event picture">
         <div class="card-body">
            <h5><a href="{{ url_for('event.show', id=event.id) }}" class="card-title">{{ event.name }}</a></h5>
            <p class="card-text">{{ event.date }} {{ event.time }} <br>
               {{ event.location }} <br>
               Status: 
               <button type="button" class="btn
               {% if event.status|lower == 'closed' %}btn-danger
               {% elif event.status|lower == 'sold out' %}btn-warning
               {% elif event.status|lower == 'open' %}btn-success
               {% endif %}">{{ event.status }}</button>
            </p>
            {% if event.owner_id != current_user.id %}
            <a href="#" class="btn btn-secondary" disabled>Edit</a>
            {% else %}
            <a href="{{ url_for('event.manage', event_id=event.id) }}" class="btn btn-primary">Edit</a>
            {% endif %}
         </div>
         <div class="card-footer"><small class="text-muted">Last updated at
               {{event.last_updated.strftime('%d/%m %H:%M')}}</small></div>
      </div>
   {% endfor %}
   </div>

</div>
<script>
   var button = document.getElementById("randomNumber");
   let x = 1;
   button.addEventListener("click", function () {
      var x = Math.floor(Math.random() * 11) + 1;
      window.location.href = "http://127.0.0.1:5000/events/" + x;
   });
</script>
{% endblock %}

a3_group53/EventsAround/templates/user.html
{% extends "base.html" %}
{% import "bootstrap4/form.html" as wtf %}

{% block content %}

<div class="container-fluid">
<div class="page-header">
    <h4>{{heading}}</h4>
</div>

<!-- flashes any messages to the user -->
{% with messages = get_flashed_messages() %}
{% if messages %} <!-- check if there are any messages -->
  <div class="container-fluid">
    <div class="row mt-3 mb-3">
      <div class="col-md-12">
      {% for message in messages %} <!--loop through the messages-->
        <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}
{% endwith %}

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6 ml-5">
{{wtf.render_form(form)}}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4 mb-5 ml-5">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endif %}
</div>
{% endblock %}